import type { Lead, LeadTypeMeta } from "./types";

export const LEAD_TYPES: LeadTypeMeta[] = [
  { id: "expired", label: "Expired Listing", classification: "warm", blurb: "Removed from MLS without a sale — owner may be motivated to relist" },
  { id: "fsbo", label: "FSBO", classification: "warm", blurb: "For Sale By Owner — actively on market, may need representation" },
  { id: "form_fill", label: "Form Fill / Ad Click", classification: "warm", blurb: "Engaged with real estate marketing materials" },
  { id: "home_value", label: "Home Value Inquiry", classification: "warm", blurb: "Requested an automated valuation or CMA" },
  { id: "life_event", label: "Life Event", classification: "warm", blurb: "Recently engaged, married, divorced, or growing family" },
  { id: "relocation", label: "Relocation Signal", classification: "warm", blurb: "Job change or new employer in a different metro" },
  { id: "past_client", label: "Past Client", classification: "warm", blurb: "Approaching the typical 5–7 year re-purchase window" },
  { id: "high_equity", label: "High Equity", classification: "cold", blurb: "40%+ equity — may sell to unlock capital" },
  { id: "long_term", label: "Long-Term Owner", classification: "cold", blurb: "Owned 10+ years — may be ready to downsize or move" },
  { id: "absentee", label: "Absentee Owner", classification: "cold", blurb: "Does not live at the subject property" },
  { id: "pre_foreclosure", label: "Pre-Foreclosure / NOD", classification: "cold", blurb: "Received a Notice of Default — may need to sell quickly" },
  { id: "probate", label: "Probate", classification: "cold", blurb: "Estate property that may be sold during settlement" },
  { id: "absentee_landlord", label: "Absentee Landlord", classification: "cold", blurb: "Non-local rental owner who may be open to selling" },
  { id: "empty_nester", label: "Empty Nester", classification: "cold", blurb: "Older homeowner, downsizing candidate" },
  { id: "investor", label: "Multi-Property Investor", classification: "cold", blurb: "Owns 2+ properties — potential buyer or portfolio seller" },
];

export const leadTypeMeta = (id: Lead["leadType"]): LeadTypeMeta =>
  LEAD_TYPES.find((t) => t.id === id)!;

export const SEED_LEADS: Lead[] = [
  {
    id: "L-1042",
    ownerName: "Sandra & Mike Whitfield",
    address: "1814 Lombardy Cir",
    city: "Charlotte", state: "NC", zip: "28203",
    leadType: "expired",
    strengths: { intent: 0.95, lifeEvent: 0.55, property: 0.85, marketTiming: 0.8, contactQuality: 1 },
    reasoning: "Listing expired 9 days ago after 87 days on market. Owners bought 11 years ago and listed above neighborhood comps — strong odds they still want to sell at a corrected price.",
    signals: [
      { category: "intent", text: "MLS listing expired May 28 after 87 days on market with two price cuts" },
      { category: "lifeEvent", text: "County record shows a second property purchased in Fort Mill, SC in March" },
      { category: "property", text: "Est. 64% equity; owned 11 years; assessed value up 22% since 2022" },
      { category: "marketTiming", text: "Dilworth median days-on-market is 19 — well-priced homes are moving" },
      { category: "contactQuality", text: "Verified mobile and email on file; number is clear of the DNC registry" },
    ],
    property: { type: "Single Family", beds: 4, baths: 3, sqft: 2640, yearBuilt: 1998, estValue: 685000, assessedValue: 612000, equityPct: 64, ownershipYears: 11, lastSalePrice: 318000, lastSaleDate: "2015-04-17" },
    contact: { phone: "(704) 555-0114", phoneVerified: true, dncStatus: "clear", email: "swhitfield@example.com", emailVerified: true, consent: "none" },
    source: "MLS via RESO Web API",
    stage: "new", tags: ["Dilworth", "Relist candidate"],
    notes: [],
    surfacedAt: "2026-06-11",
  },
  {
    id: "L-1038",
    ownerName: "Priya Raghavan",
    address: "412 E Tremont Ave #2B",
    city: "Charlotte", state: "NC", zip: "28203",
    leadType: "home_value",
    strengths: { intent: 0.9, lifeEvent: 0.7, property: 0.6, marketTiming: 0.7, contactQuality: 1 },
    reasoning: "Requested a home value report Tuesday night and opened the follow-up email twice. Recently married per public records — a classic move-up signal.",
    signals: [
      { category: "intent", text: "Submitted home value inquiry June 9 at 9:42 PM; opened report twice" },
      { category: "lifeEvent", text: "Marriage license recorded in Mecklenburg County, February 2026" },
      { category: "property", text: "Condo owned 5 years with est. 48% equity" },
      { category: "marketTiming", text: "South End condo inventory at a 14-month low" },
      { category: "contactQuality", text: "Opt-in email + verified mobile from form fill" },
    ],
    property: { type: "Condo", beds: 2, baths: 2, sqft: 1180, yearBuilt: 2014, estValue: 415000, assessedValue: 388000, equityPct: 48, ownershipYears: 5, lastSalePrice: 262000, lastSaleDate: "2021-03-02" },
    contact: { phone: "(980) 555-0167", phoneVerified: true, dncStatus: "clear", email: "priya.r@example.com", emailVerified: true, consent: "opt_in" },
    source: "Home value form — prospectiq.com",
    stage: "contacted", tags: ["Move-up buyer"],
    notes: [{ date: "2026-06-10", text: "Left voicemail; mentioned the report she requested. Try again Thursday." }],
    reminder: "2026-06-12",
    surfacedAt: "2026-06-09",
  },
  {
    id: "L-1029",
    ownerName: "Gerald Okafor",
    address: "2207 Mallard Grove Ln",
    city: "Huntersville", state: "NC", zip: "28078",
    leadType: "fsbo",
    strengths: { intent: 1, lifeEvent: 0.3, property: 0.7, marketTiming: 0.75, contactQuality: 0.8 },
    reasoning: "FSBO listed 24 days ago with no price movement and stale photos. Historically ~80% of FSBOs end up listing with an agent — this one is approaching that decision point.",
    signals: [
      { category: "intent", text: "Active FSBO on Zillow for 24 days, no offers indicated" },
      { category: "property", text: "Est. 55% equity; priced 6% above the model's estimate" },
      { category: "marketTiming", text: "Huntersville DOM rising — overpriced homes sitting longer" },
      { category: "contactQuality", text: "Listing phone verified via carrier lookup; DNC clear" },
    ],
    property: { type: "Single Family", beds: 5, baths: 4, sqft: 3310, yearBuilt: 2006, estValue: 612000, assessedValue: 560000, equityPct: 55, ownershipYears: 8, lastSalePrice: 389000, lastSaleDate: "2018-06-30" },
    contact: { phone: "(704) 555-0182", phoneVerified: true, dncStatus: "clear", email: undefined, emailVerified: false, consent: "none" },
    source: "FSBO aggregation partner",
    stage: "new", tags: [],
    notes: [],
    surfacedAt: "2026-06-11",
  },
  {
    id: "L-1019",
    ownerName: "The Castellano Family Trust",
    address: "914 Berkeley Ave",
    city: "Charlotte", state: "NC", zip: "28203",
    leadType: "probate",
    strengths: { intent: 0.2, lifeEvent: 0.9, property: 0.9, marketTiming: 0.6, contactQuality: 0.5 },
    reasoning: "Estate filed in probate court in April; the property transferred to a family trust. The executor lives out of state, which often means a sale during settlement.",
    signals: [
      { category: "lifeEvent", text: "Probate case #26-E-1187 filed April 14; property deeded to trust" },
      { category: "property", text: "Owned 31 years, free and clear (est. 100% equity)" },
      { category: "marketTiming", text: "Dilworth buyer demand strong; estate homes drawing multiple offers" },
      { category: "contactQuality", text: "Executor mailing address on file in Atlanta, GA; no verified phone" },
    ],
    property: { type: "Single Family", beds: 3, baths: 2, sqft: 1980, yearBuilt: 1947, estValue: 740000, assessedValue: 655000, equityPct: 100, ownershipYears: 31, lastSalePrice: 145000, lastSaleDate: "1995-02-10" },
    contact: { phone: undefined, phoneVerified: false, dncStatus: "clear", email: "estate.castellano@example.com", emailVerified: false, consent: "none" },
    source: "Mecklenburg County probate records",
    stage: "new", tags: ["Estate", "Out-of-state executor"],
    notes: [],
    surfacedAt: "2026-06-10",
  },
  {
    id: "L-1007",
    ownerName: "Marcus & Dana Hollis",
    address: "3528 Commonwealth Ave",
    city: "Charlotte", state: "NC", zip: "28205",
    leadType: "pre_foreclosure",
    strengths: { intent: 0.45, lifeEvent: 0.6, property: 0.8, marketTiming: 0.65, contactQuality: 0.6 },
    reasoning: "Notice of Default recorded 17 days ago, but the owners hold roughly 58% equity — a strong candidate for a pre-foreclosure sale that protects their position.",
    signals: [
      { category: "intent", text: "NOD recorded May 25; reinstatement window open" },
      { category: "lifeEvent", text: "Employer layoff filings in March match household (WARN notice)" },
      { category: "property", text: "Est. 58% equity — sale could clear the default and preserve six figures" },
      { category: "marketTiming", text: "Plaza Midwood comps closing within 3% of ask" },
      { category: "contactQuality", text: "Landline on file, DNC clear; no verified email" },
    ],
    property: { type: "Single Family", beds: 3, baths: 2, sqft: 1750, yearBuilt: 1952, estValue: 498000, assessedValue: 441000, equityPct: 58, ownershipYears: 9, lastSalePrice: 287000, lastSaleDate: "2017-08-21" },
    contact: { phone: "(704) 555-0139", phoneVerified: false, dncStatus: "clear", email: undefined, emailVerified: false, consent: "none" },
    source: "County recorder — NOD filings",
    stage: "contacted", tags: ["Time-sensitive", "Equity rescue"],
    notes: [{ date: "2026-06-08", text: "Spoke with Dana briefly — guarded but didn't hang up. Sent a handwritten note." }],
    reminder: "2026-06-15",
    surfacedAt: "2026-05-27",
  },
  {
    id: "L-0991",
    ownerName: "Eleanor Vance",
    address: "7104 Quail Hollow Rd",
    city: "Charlotte", state: "NC", zip: "28210",
    leadType: "empty_nester",
    strengths: { intent: 0.1, lifeEvent: 0.65, property: 0.95, marketTiming: 0.55, contactQuality: 0.8 },
    reasoning: "Owned 26 years with the home now far larger than the household. No intent signals yet — a nurture candidate, not a cold call priority.",
    signals: [
      { category: "lifeEvent", text: "Household size model indicates children moved out (voter + DMV records)" },
      { category: "property", text: "4,100 sqft on 0.6 acres; owned 26 years; est. 91% equity" },
      { category: "marketTiming", text: "Quail Hollow large-lot homes seeing renewed buyer interest" },
      { category: "contactQuality", text: "Verified landline; DNC clear" },
    ],
    property: { type: "Single Family", beds: 5, baths: 4, sqft: 4100, yearBuilt: 1989, estValue: 1120000, assessedValue: 980000, equityPct: 91, ownershipYears: 26, lastSalePrice: 310000, lastSaleDate: "2000-05-12" },
    contact: { phone: "(704) 555-0121", phoneVerified: true, dncStatus: "clear", email: undefined, emailVerified: false, consent: "none" },
    source: "Public county records + ATTOM",
    stage: "new", tags: ["Downsizer"],
    notes: [],
    surfacedAt: "2026-06-08",
  },
  {
    id: "L-0987",
    ownerName: "Tom & Reiko Akagi",
    address: "5916 Closeburn Rd",
    city: "Charlotte", state: "NC", zip: "28210",
    leadType: "past_client",
    strengths: { intent: 0.35, lifeEvent: 0.8, property: 0.75, marketTiming: 0.7, contactQuality: 1 },
    reasoning: "You closed their purchase 6 years ago — squarely in the 5–7 year re-purchase window. A second child was born last year; they're likely outgrowing the house.",
    signals: [
      { category: "intent", text: "Opened your spring market update email 3 times" },
      { category: "lifeEvent", text: "Birth record (2025) — second child; 3BR home now likely tight" },
      { category: "property", text: "Est. 51% equity since 2020 purchase" },
      { category: "marketTiming", text: "Move-up spread in Montclaire is favorable vs. 2024" },
      { category: "contactQuality", text: "Opt-in contact — past client relationship on file" },
    ],
    property: { type: "Single Family", beds: 3, baths: 2, sqft: 1620, yearBuilt: 1962, estValue: 442000, assessedValue: 405000, equityPct: 51, ownershipYears: 6, lastSalePrice: 295000, lastSaleDate: "2020-07-15" },
    contact: { phone: "(980) 555-0153", phoneVerified: true, dncStatus: "clear", email: "akagi.fam@example.com", emailVerified: true, consent: "opt_in" },
    source: "Your CRM import + public records",
    stage: "appointment", tags: ["Past client", "Move-up buyer"],
    notes: [{ date: "2026-06-05", text: "Coffee scheduled Sat 10am at Not Just Coffee. Bring Montclaire comps." }],
    reminder: "2026-06-13",
    surfacedAt: "2026-06-02",
  },
  {
    id: "L-0978",
    ownerName: "Bluestone Holdings LLC",
    address: "1530 Pegram St",
    city: "Charlotte", state: "NC", zip: "28205",
    leadType: "absentee_landlord",
    strengths: { intent: 0.15, lifeEvent: 0.2, property: 0.85, marketTiming: 0.75, contactQuality: 0.7 },
    reasoning: "Out-of-state LLC has held this rental 14 years and just lost its tenant (utility shutoff signal). Landlords without local management often sell at vacancy.",
    signals: [
      { category: "property", text: "Owned 14 years; est. 78% equity; registered to a Nashville, TN address" },
      { category: "intent", text: "Utility account closed May 30 — likely vacancy" },
      { category: "marketTiming", text: "Villa Heights investor resale prices up 9% YoY" },
      { category: "contactQuality", text: "LLC registered agent phone on file; DNC clear" },
    ],
    property: { type: "Duplex", beds: 4, baths: 2, sqft: 2080, yearBuilt: 1941, estValue: 520000, assessedValue: 462000, equityPct: 78, ownershipYears: 14, lastSalePrice: 118000, lastSaleDate: "2012-01-20" },
    contact: { phone: "(615) 555-0148", phoneVerified: true, dncStatus: "clear", email: "mgmt@bluestoneholdings.example.com", emailVerified: false, consent: "none" },
    source: "County assessor + utility data partner",
    stage: "new", tags: ["Investor-owned", "Likely vacant"],
    notes: [],
    surfacedAt: "2026-06-07",
  },
  {
    id: "L-0969",
    ownerName: "Denise Carmichael",
    address: "824 Lunsford Pl",
    city: "Charlotte", state: "NC", zip: "28205",
    leadType: "life_event",
    strengths: { intent: 0.5, lifeEvent: 0.95, property: 0.55, marketTiming: 0.6, contactQuality: 0.9 },
    reasoning: "Divorce filing finalized in May involving a jointly-owned home. One party typically buys out or both sell — either way, representation is needed soon.",
    signals: [
      { category: "lifeEvent", text: "Divorce decree recorded May 19; property jointly titled" },
      { category: "intent", text: "Visited two open houses in NoDa last weekend (sign-in data)" },
      { category: "property", text: "Owned 7 years; est. 44% equity" },
      { category: "marketTiming", text: "NoDa entry-level inventory tightening" },
      { category: "contactQuality", text: "Verified mobile; DNC clear; no consent yet" },
    ],
    property: { type: "Single Family", beds: 3, baths: 2, sqft: 1490, yearBuilt: 1955, estValue: 451000, assessedValue: 410000, equityPct: 44, ownershipYears: 7, lastSalePrice: 289000, lastSaleDate: "2019-04-03" },
    contact: { phone: "(704) 555-0173", phoneVerified: true, dncStatus: "clear", email: "dcarmichael@example.com", emailVerified: false, consent: "none" },
    source: "Public court records + open house partner",
    stage: "new", tags: [],
    notes: [],
    surfacedAt: "2026-06-10",
  },
  {
    id: "L-0954",
    ownerName: "Hank & Lorraine Pruitt",
    address: "11220 Five Cedars Rd",
    city: "Charlotte", state: "NC", zip: "28226",
    leadType: "long_term",
    strengths: { intent: 0.05, lifeEvent: 0.4, property: 0.9, marketTiming: 0.5, contactQuality: 0.4 },
    reasoning: "Owned 22 years with deep equity, but no intent or life-event signals. Profile-match only — best suited to a long-run nurture sequence.",
    signals: [
      { category: "property", text: "Owned 22 years; est. 88% equity; assessed value up 31% since 2021" },
      { category: "lifeEvent", text: "Age band 60–70 per public records — possible retirement horizon" },
      { category: "marketTiming", text: "South Charlotte trade-down inventory improving" },
      { category: "contactQuality", text: "Phone on file is on the DNC registry — calls blocked; mail or door-knock only" },
    ],
    property: { type: "Single Family", beds: 4, baths: 3, sqft: 2890, yearBuilt: 1996, estValue: 760000, assessedValue: 672000, equityPct: 88, ownershipYears: 22, lastSalePrice: 264000, lastSaleDate: "2004-09-28" },
    contact: { phone: "(704) 555-0190", phoneVerified: true, dncStatus: "listed", email: undefined, emailVerified: false, consent: "none" },
    source: "Public county records + ATTOM",
    stage: "new", tags: ["Mail campaign"],
    notes: [],
    surfacedAt: "2026-06-06",
  },
  {
    id: "L-0948",
    ownerName: "Ifeoma Adeyemi",
    address: "208 Skyview Ter",
    city: "Matthews", state: "NC", zip: "28105",
    leadType: "relocation",
    strengths: { intent: 0.75, lifeEvent: 0.85, property: 0.5, marketTiming: 0.65, contactQuality: 0.9 },
    reasoning: "Accepted a role at a Dallas-based employer per professional network signals, and her home hit our pre-listing checklist (new roof permit, landscaping spend).",
    signals: [
      { category: "lifeEvent", text: "New employer in Dallas–Fort Worth metro announced May 2026" },
      { category: "intent", text: "Roof replacement permit pulled June 2 — common pre-listing prep" },
      { category: "property", text: "Owned 6 years; est. 42% equity" },
      { category: "marketTiming", text: "Matthews sellers averaging 99.1% of list price" },
      { category: "contactQuality", text: "Verified mobile + email; DNC clear" },
    ],
    property: { type: "Townhouse", beds: 3, baths: 3, sqft: 1860, yearBuilt: 2016, estValue: 398000, assessedValue: 371000, equityPct: 42, ownershipYears: 6, lastSalePrice: 276000, lastSaleDate: "2020-02-14" },
    contact: { phone: "(704) 555-0160", phoneVerified: true, dncStatus: "clear", email: "ifeoma.a@example.com", emailVerified: true, consent: "none" },
    source: "Permissioned data partner",
    stage: "contacted", tags: ["Relocating", "Listing opportunity"],
    notes: [{ date: "2026-06-09", text: "Texted intro (she replied!). Wants to talk after her offer letter finalizes." }],
    reminder: "2026-06-16",
    surfacedAt: "2026-06-05",
  },
  {
    id: "L-0931",
    ownerName: "Raymond Tisdale",
    address: "4419 Emory Ln",
    city: "Charlotte", state: "NC", zip: "28209",
    leadType: "high_equity",
    strengths: { intent: 0.1, lifeEvent: 0.25, property: 0.95, marketTiming: 0.7, contactQuality: 0.85 },
    reasoning: "Est. 83% equity in a fast-appreciating pocket of SouthPark. No direct intent — a strong equity-unlock conversation for a nurture track.",
    signals: [
      { category: "property", text: "Est. 83% equity; value up 18% in 24 months" },
      { category: "marketTiming", text: "SouthPark scarcity premium at a 3-year high" },
      { category: "lifeEvent", text: "No recent life-event records" },
      { category: "contactQuality", text: "Verified mobile; DNC clear" },
    ],
    property: { type: "Single Family", beds: 4, baths: 3, sqft: 2510, yearBuilt: 1978, estValue: 815000, assessedValue: 742000, equityPct: 83, ownershipYears: 13, lastSalePrice: 392000, lastSaleDate: "2013-05-30" },
    contact: { phone: "(704) 555-0102", phoneVerified: true, dncStatus: "clear", email: "rtisdale@example.com", emailVerified: false, consent: "none" },
    source: "Public county records + ATTOM",
    stage: "new", tags: ["SouthPark"],
    notes: [],
    surfacedAt: "2026-06-09",
  },
  {
    id: "L-0917",
    ownerName: "Calloway Properties Group",
    address: "933 Seigle Ave",
    city: "Charlotte", state: "NC", zip: "28205",
    leadType: "investor",
    strengths: { intent: 0.4, lifeEvent: 0.1, property: 0.8, marketTiming: 0.8, contactQuality: 0.75 },
    reasoning: "Owns 7 properties in Mecklenburg County and sold two in the last 90 days — an active portfolio rebalancer worth a direct conversation.",
    signals: [
      { category: "intent", text: "Sold 2 of 9 portfolio properties since March — active disposition pattern" },
      { category: "property", text: "7 remaining properties; subject parcel est. 71% equity" },
      { category: "marketTiming", text: "Belmont/Optimist Park investor demand outpacing supply" },
      { category: "contactQuality", text: "Principal's direct line verified; DNC clear" },
    ],
    property: { type: "Single Family", beds: 2, baths: 1, sqft: 1040, yearBuilt: 1938, estValue: 372000, assessedValue: 330000, equityPct: 71, ownershipYears: 9, lastSalePrice: 96000, lastSaleDate: "2017-03-11" },
    contact: { phone: "(704) 555-0195", phoneVerified: true, dncStatus: "clear", email: "acq@callowayprops.example.com", emailVerified: true, consent: "none" },
    source: "County assessor portfolio analysis",
    stage: "contacted", tags: ["Portfolio seller"],
    notes: [{ date: "2026-06-04", text: "Gatekeeper took a message. Try the principal before 9am." }],
    surfacedAt: "2026-06-01",
  },
  {
    id: "L-0902",
    ownerName: "Beatrice Lindqvist",
    address: "2818 Shamrock Dr",
    city: "Charlotte", state: "NC", zip: "28205",
    leadType: "form_fill",
    strengths: { intent: 0.85, lifeEvent: 0.45, property: 0.5, marketTiming: 0.6, contactQuality: 0.95 },
    reasoning: "Clicked your 'What's my home worth?' ad and completed the full form including timeline — selected 'within 6 months.' That self-reported timeline is gold.",
    signals: [
      { category: "intent", text: "Completed ad-click form June 8; self-reported 6-month selling timeline" },
      { category: "lifeEvent", text: "Recently retired per employer separation record" },
      { category: "property", text: "Owned 9 years; est. 49% equity" },
      { category: "marketTiming", text: "Country Club Heights buyer searches up 12% MoM" },
      { category: "contactQuality", text: "Opt-in form fill — consent on record; verified mobile + email" },
    ],
    property: { type: "Single Family", beds: 3, baths: 2, sqft: 1580, yearBuilt: 1958, estValue: 412000, assessedValue: 376000, equityPct: 49, ownershipYears: 9, lastSalePrice: 233000, lastSaleDate: "2017-10-09" },
    contact: { phone: "(980) 555-0136", phoneVerified: true, dncStatus: "clear", email: "b.lindqvist@example.com", emailVerified: true, consent: "opt_in" },
    source: "Ad click — Meta lead form",
    stage: "new", tags: ["6-month timeline"],
    notes: [],
    surfacedAt: "2026-06-08",
  },
  {
    id: "L-0894",
    ownerName: "Walter & June Ostrander",
    address: "6310 Rosecrest Dr",
    city: "Charlotte", state: "NC", zip: "28210",
    leadType: "absentee",
    strengths: { intent: 0.1, lifeEvent: 0.3, property: 0.75, marketTiming: 0.55, contactQuality: 0.3 },
    reasoning: "Tax bill mails to a Sarasota, FL address while the home sits occupied by renters. Moderate profile match; weak contact data drags the score down.",
    signals: [
      { category: "property", text: "Owner mailing address in Sarasota, FL; owned 16 years; est. 69% equity" },
      { category: "marketTiming", text: "Starmount rental yields compressing — sell signals rising" },
      { category: "lifeEvent", text: "No recent life-event records" },
      { category: "contactQuality", text: "No verified phone; postal address only" },
    ],
    property: { type: "Single Family", beds: 3, baths: 1, sqft: 1290, yearBuilt: 1961, estValue: 348000, assessedValue: 322000, equityPct: 69, ownershipYears: 16, lastSalePrice: 142000, lastSaleDate: "2010-06-25" },
    contact: { phone: undefined, phoneVerified: false, dncStatus: "clear", email: undefined, emailVerified: false, consent: "none" },
    source: "County assessor mailing records",
    stage: "new", tags: ["Mail campaign"],
    notes: [],
    surfacedAt: "2026-06-04",
  },
  {
    id: "L-0881",
    ownerName: "Chen & Amara Liu-Diallo",
    address: "1126 Ideal Way",
    city: "Charlotte", state: "NC", zip: "28203",
    leadType: "life_event",
    strengths: { intent: 0.6, lifeEvent: 0.9, property: 0.65, marketTiming: 0.7, contactQuality: 0.9 },
    reasoning: "Building permit for a nursery conversion plus a recorded birth — growing family in a 2-bedroom bungalow. High-probability move-up sellers within 12 months.",
    signals: [
      { category: "lifeEvent", text: "Birth record April 2026; permit filed to convert office to nursery" },
      { category: "intent", text: "Browsing 4BR listings on partner portal (anonymized cohort match)" },
      { category: "property", text: "Owned 4 years; est. 39% equity in appreciating Dilworth pocket" },
      { category: "marketTiming", text: "2BR bungalow demand near all-time high — strong sale leverage" },
      { category: "contactQuality", text: "Verified mobile + email; DNC clear" },
    ],
    property: { type: "Bungalow", beds: 2, baths: 1, sqft: 1110, yearBuilt: 1936, estValue: 525000, assessedValue: 478000, equityPct: 39, ownershipYears: 4, lastSalePrice: 405000, lastSaleDate: "2022-05-20" },
    contact: { phone: "(704) 555-0128", phoneVerified: true, dncStatus: "clear", email: "liudiallo@example.com", emailVerified: true, consent: "none" },
    source: "Public records + permit data",
    stage: "appointment", tags: ["Move-up buyer", "Dilworth"],
    notes: [{ date: "2026-06-07", text: "Listing consult booked June 14, 2pm. They also want buyer rep for 4BRs near Sedgefield." }],
    reminder: "2026-06-14",
    surfacedAt: "2026-05-30",
  },
  {
    id: "L-0860",
    ownerName: "Dorothy Greer",
    address: "519 Wakefield Dr",
    city: "Charlotte", state: "NC", zip: "28209",
    leadType: "expired",
    strengths: { intent: 0.8, lifeEvent: 0.5, property: 0.7, marketTiming: 0.75, contactQuality: 0.6 },
    reasoning: "Second expiration in 14 months — previous agent relationship clearly didn't work. Owners who re-expire convert at nearly twice the rate when approached with a new strategy.",
    signals: [
      { category: "intent", text: "Listing expired June 1 — second expiration since spring 2025" },
      { category: "property", text: "Est. 61% equity; owned 12 years" },
      { category: "marketTiming", text: "Madison Park homes priced to comps go pending in 11 days" },
      { category: "lifeEvent", text: "Property tax deferral application — possible fixed-income pressure" },
      { category: "contactQuality", text: "Landline on file; DNC clear; no email" },
    ],
    property: { type: "Ranch", beds: 3, baths: 2, sqft: 1640, yearBuilt: 1959, estValue: 489000, assessedValue: 447000, equityPct: 61, ownershipYears: 12, lastSalePrice: 215000, lastSaleDate: "2014-03-08" },
    contact: { phone: "(704) 555-0119", phoneVerified: false, dncStatus: "clear", email: undefined, emailVerified: false, consent: "none" },
    source: "MLS via RESO Web API",
    stage: "contacted", tags: ["Re-expired", "Madison Park"],
    notes: [{ date: "2026-06-03", text: "Dropped off a relisting strategy packet. She's burned out on agents — go slow." }],
    reminder: "2026-06-17",
    surfacedAt: "2026-06-01",
  },
  {
    id: "L-0845",
    ownerName: "Felix Arroyo",
    address: "3104 Card St",
    city: "Charlotte", state: "NC", zip: "28205",
    leadType: "high_equity",
    strengths: { intent: 0.05, lifeEvent: 0.15, property: 0.85, marketTiming: 0.6, contactQuality: 0.5 },
    reasoning: "Solid equity profile but zero intent or life-event signals and thin contact data. Keep in the nurture pool; not worth priority outreach time this week.",
    signals: [
      { category: "property", text: "Est. 76% equity; owned 11 years" },
      { category: "marketTiming", text: "Echo Hills appreciation steady at 6% YoY" },
      { category: "lifeEvent", text: "No recent life-event records" },
      { category: "contactQuality", text: "Unverified phone from data append; DNC clear" },
    ],
    property: { type: "Single Family", beds: 3, baths: 1, sqft: 1220, yearBuilt: 1956, estValue: 332000, assessedValue: 301000, equityPct: 76, ownershipYears: 11, lastSalePrice: 128000, lastSaleDate: "2015-09-17" },
    contact: { phone: "(704) 555-0188", phoneVerified: false, dncStatus: "clear", email: undefined, emailVerified: false, consent: "none" },
    source: "Public county records + ATTOM",
    stage: "new", tags: [],
    notes: [],
    surfacedAt: "2026-06-03",
  },
  {
    id: "L-0822",
    ownerName: "Nia & Jordan Whitaker",
    address: "8812 Windsor Ridge Dr",
    city: "Charlotte", state: "NC", zip: "28277",
    leadType: "past_client",
    strengths: { intent: 0.3, lifeEvent: 0.5, property: 0.8, marketTiming: 0.6, contactQuality: 1 },
    reasoning: "Closed with you in 2019 — year 7 of the re-purchase window. Strong equity and a recent school-zone search pattern suggest a family-driven move is forming.",
    signals: [
      { category: "intent", text: "Clicked two Ballantyne school-zone articles in your newsletter" },
      { category: "lifeEvent", text: "Eldest child enters middle school next year (household model)" },
      { category: "property", text: "Est. 57% equity since 2019 purchase" },
      { category: "marketTiming", text: "Ballantyne move-up inventory loosening" },
      { category: "contactQuality", text: "Opt-in past client; verified mobile + email" },
    ],
    property: { type: "Single Family", beds: 4, baths: 2, sqft: 2260, yearBuilt: 2001, estValue: 587000, assessedValue: 536000, equityPct: 57, ownershipYears: 7, lastSalePrice: 372000, lastSaleDate: "2019-05-24" },
    contact: { phone: "(980) 555-0144", phoneVerified: true, dncStatus: "clear", email: "whitaker.nj@example.com", emailVerified: true, consent: "opt_in" },
    source: "Your CRM import + public records",
    stage: "closed", tags: ["Past client"],
    notes: [{ date: "2026-05-22", text: "Listed and closed in 8 days at 102% of ask. Referral promised!" }],
    surfacedAt: "2026-04-12",
  },
  {
    id: "L-0810",
    ownerName: "Sycamore Row Rentals LLC",
    address: "415 N Smallwood Pl",
    city: "Charlotte", state: "NC", zip: "28216",
    leadType: "absentee_landlord",
    strengths: { intent: 0.2, lifeEvent: 0.1, property: 0.7, marketTiming: 0.7, contactQuality: 0.45 },
    reasoning: "Out-of-state landlord with a 12-year hold and rising tax burden. Borderline cold/nurture — score is held down by missing verified contact data.",
    signals: [
      { category: "property", text: "Owned 12 years; est. 66% equity; taxes up 28% at last revaluation" },
      { category: "marketTiming", text: "Wesley Heights rents flat YoY while values climb — yield squeeze" },
      { category: "intent", text: "Property management contract lapsed per partner data" },
      { category: "contactQuality", text: "Registered agent address only; no verified phone" },
    ],
    property: { type: "Single Family", beds: 3, baths: 2, sqft: 1380, yearBuilt: 1948, estValue: 387000, assessedValue: 355000, equityPct: 66, ownershipYears: 12, lastSalePrice: 131000, lastSaleDate: "2014-02-06" },
    contact: { phone: undefined, phoneVerified: false, dncStatus: "clear", email: "sycamorerow@example.com", emailVerified: false, consent: "none" },
    source: "County assessor + data partner",
    stage: "new", tags: ["Investor-owned"],
    notes: [],
    surfacedAt: "2026-06-02",
  },
];
